name: Tests

on:
  push:
  pull_request:
    branches: [master, main]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Test C#
        run: dotnet test ./csharp/AdventOfCode/AdventOfCode.sln

      # - name: Test Java
      #   run: |
      #     cd java/AdventOfCode/src
      #     java ./aoc/year2018/Day01/Day01.java
      #     java ./aoc/year2019/Day02/Day02.java

      - name: Test JavaScript
        run: |
          node ./javascript/AdventOfCode/src/AoC2018/Day01/Day01.js
          node ./javascript/AdventOfCode/src/AoC2019/Day01/Day01.js
          node ./javascript/AdventOfCode/src/AoC2019/Day02/Day02.js
          node ./javascript/AdventOfCode/src/AoC2019/Day04/Day04.js
          node ./javascript/AdventOfCode/src/AoC2019/Day04/Day04b.js

      - name: Test Perl
        run: |
          perl ./perl/2018/Day01/Day01.pl
          perl ./perl/2019/Day02/Day02.pl

      - name: Test Swift
        run: |
          swift ./swift/2018/Sources/Day01.swift
          swift ./swift/2019/Sources/Day02.swift

      # - name: Test TypeScript
      #   run: |
      #     deno --allow-read ./typescript/2018/src/Day01.ts
