name: Test Coverage

on:
  push:
  pull_request:
    branches: [master, main]
  
jobs:
  dotnet-tests:
    name: Run C# Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore --configuration Release

      - name: Run tests with coverage
        run: |
          dotnet test --no-build --configuration Release \
            --collect:"XPlat Code Coverage"

      - name: Publish coverage report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: '**/coverage.cobertura.xml'

  javascript-tests:
    name: Run JavaScript Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd 2019/day02/javascript
          npm install

      - name: Run tests
        run: |
          cd 2019/day02/javascript
          npm test -- --coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: javascript-coverage
          path: 2019/day02/javascript/coverage