name: Test Swift

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  swift-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Platform check
        run: uname -a

      - name: swift info
        run: swift --version

      - name: Build 2020
        run: |
          cd Swift/2020/
          swift build -v

      - name: Run tests 2020
        run: |
          cd Swift/2020/
          swift test -v
        